---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rackspace-system

resources:
  - '../../../../../fleet-apps/kustomize/base/external-dns'
  - './configmap.yaml'
patchesStrategicMerge:
  - './deployment.yaml'
