---
# Source: external-dns/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: default
  labels: 
    app.kubernetes.io/name: external-dns
    helm.sh/chart: external-dns-5.4.11
    app.kubernetes.io/instance: external-dns
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true

